/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.onyx.yandexbooks;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int btn_eink_text_color=0x7f040008;
        public static final int eink_black=0x7f040001;
        public static final int eink_border=0x7f040006;
        public static final int eink_dark_gray=0x7f040002;
        public static final int eink_divider=0x7f040005;
        public static final int eink_gray=0x7f040003;
        public static final int eink_highlight=0x7f040007;
        public static final int eink_light_gray=0x7f040004;
        public static final int eink_white=0x7f040000;
    }
    public static final class drawable {
        public static final int badge_downloaded=0x7f020000;
        public static final int btn_eink=0x7f020001;
        public static final int btn_eink_primary=0x7f020002;
        public static final int cover_border=0x7f020003;
        public static final int ic_launcher=0x7f020004;
        public static final int progress_eink_bar=0x7f020005;
        public static final int tab_eink_active=0x7f020006;
        public static final int tab_eink_inactive=0x7f020007;
    }
    public static final class id {
        public static final int auth_webview=0x7f07000c;
        public static final int auth_webview_tip=0x7f07000b;
        public static final int book_annotation=0x7f07004f;
        public static final int book_author=0x7f07004e;
        public static final int book_cover=0x7f07004c;
        public static final int book_download_btn=0x7f070054;
        public static final int book_progress=0x7f070051;
        public static final int book_progress_bar=0x7f070050;
        public static final int book_read_btn=0x7f070053;
        public static final int book_status_tag=0x7f070052;
        public static final int book_title=0x7f07004d;
        public static final int books_list_view=0x7f07001a;
        public static final int btn_check_update=0x7f07000f;
        public static final int btn_close_webview=0x7f070007;
        public static final int btn_font_decrease=0x7f070038;
        public static final int btn_font_increase=0x7f07003a;
        public static final int btn_import_file=0x7f070004;
        public static final int btn_main_menu=0x7f070010;
        public static final int btn_native_input=0x7f070009;
        public static final int btn_next_chapter=0x7f07002e;
        public static final int btn_open_keyboard=0x7f070008;
        public static final int btn_open_webview=0x7f070000;
        public static final int btn_prev_chapter=0x7f07002d;
        public static final int btn_reader_back=0x7f070026;
        public static final int btn_reader_close_overlay=0x7f070029;
        public static final int btn_reader_refresh=0x7f070028;
        public static final int btn_refresh_shelf=0x7f07001e;
        public static final int btn_reload_webview=0x7f07000a;
        public static final int btn_search_submit=0x7f070017;
        public static final int btn_shelf_next_page=0x7f070023;
        public static final int btn_shelf_prev_page=0x7f070021;
        public static final int btn_slider_page_back=0x7f07002f;
        public static final int btn_slider_page_forward=0x7f070031;
        public static final int btn_subtab_format=0x7f070035;
        public static final int btn_subtab_spacing=0x7f070036;
        public static final int btn_subtab_view=0x7f070034;
        public static final int btn_tab_format=0x7f070048;
        public static final int btn_tab_progress=0x7f070047;
        public static final int btn_tab_toc=0x7f070046;
        public static final int btn_toggle_contrast=0x7f07003f;
        public static final int btn_toggle_eink_contrast=0x7f070041;
        public static final int btn_toggle_font_family=0x7f07003c;
        public static final int btn_toggle_hyphenation=0x7f070040;
        public static final int btn_toggle_indent=0x7f07003d;
        public static final int btn_toggle_line_spacing=0x7f070043;
        public static final int btn_toggle_margins=0x7f070044;
        public static final int btn_toggle_reader_mode=0x7f07000e;
        public static final int btn_toggle_vert_margins=0x7f070045;
        public static final int empty_shelf_hint_view=0x7f07001d;
        public static final int empty_shelf_title_view=0x7f07001c;
        public static final int empty_state_container=0x7f07001b;
        public static final int font_size_label=0x7f07003b;
        public static final int layout_subtab_format_container=0x7f07003e;
        public static final int layout_subtab_spacing_container=0x7f070042;
        public static final int layout_subtab_view_container=0x7f070037;
        public static final int loading_text=0x7f070019;
        public static final int local_url_text=0x7f070003;
        public static final int manual_token_button=0x7f070005;
        public static final int qr_image=0x7f070001;
        public static final int reader_book_title_top=0x7f070027;
        public static final int reader_bottom_bar=0x7f07002b;
        public static final int reader_canvas=0x7f070024;
        public static final int reader_chapter_title_view=0x7f07002c;
        public static final int reader_format_panel=0x7f070033;
        public static final int reader_loading_overlay=0x7f070049;
        public static final int reader_loading_progress=0x7f07004a;
        public static final int reader_loading_text=0x7f07004b;
        public static final int reader_page_counter=0x7f070032;
        public static final int reader_page_seekbar=0x7f070030;
        public static final int reader_top_bar=0x7f070025;
        public static final int reader_top_divider=0x7f07002a;
        public static final int retry_button=0x7f070006;
        public static final int search_bar_container=0x7f070015;
        public static final int search_bar_divider=0x7f070018;
        public static final int search_query_input=0x7f070016;
        public static final int seekbar_font_size=0x7f070039;
        public static final int shelf_footer_bar=0x7f07001f;
        public static final int shelf_footer_status=0x7f070020;
        public static final int shelf_page_indicator=0x7f070022;
        public static final int status_text=0x7f070002;
        public static final int tab_catalog_btn=0x7f070013;
        public static final int tab_reading_btn=0x7f070011;
        public static final int tab_search_btn=0x7f070014;
        public static final int tab_to_read_btn=0x7f070012;
        public static final int webview_progress=0x7f07000d;
    }
    public static final class layout {
        public static final int activity_auth=0x7f030000;
        public static final int activity_auth_webview=0x7f030001;
        public static final int activity_main=0x7f030002;
        public static final int activity_reader=0x7f030003;
        public static final int item_book=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int auth_btn_import_file=0x7f05000e;
        public static final int auth_btn_webview=0x7f05000d;
        public static final int auth_cloud_desc=0x7f050010;
        public static final int auth_manual_token=0x7f05000a;
        public static final int auth_manual_token_hint=0x7f05000c;
        public static final int auth_manual_token_title=0x7f05000b;
        /**  Авторизация 
         */
        public static final int auth_qr_prompt=0x7f050006;
        public static final int auth_retry=0x7f050009;
        public static final int auth_success=0x7f050008;
        public static final int auth_waiting=0x7f050007;
        public static final int auth_webview_desc=0x7f05000f;
        public static final int btn_cancel=0x7f050012;
        public static final int btn_download=0x7f05001e;
        public static final int btn_jump=0x7f05001c;
        public static final int btn_logout=0x7f050013;
        public static final int btn_read=0x7f050019;
        public static final int btn_refresh=0x7f050018;
        public static final int btn_save=0x7f050011;
        public static final int btn_stay=0x7f05001d;
        public static final int empty_shelf_hint=0x7f050017;
        public static final int empty_shelf_title=0x7f050016;
        public static final int epd_refresh_rate=0x7f050023;
        public static final int font_size=0x7f050020;
        public static final int hyphenation_toggle=0x7f050022;
        public static final int line_spacing=0x7f050021;
        public static final int logout_confirm_message=0x7f050015;
        public static final int logout_confirm_title=0x7f050014;
        /**  Читалка и типографика 
         */
        public static final int settings_typography=0x7f05001f;
        public static final int sync_conflict_message=0x7f05001b;
        /**  Синхронизация и конфликты 
         */
        public static final int sync_conflict_title=0x7f05001a;
        public static final int tab_done=0x7f050005;
        /**  Вкладки полок 
         */
        public static final int tab_reading=0x7f050003;
        public static final int tab_to_read=0x7f050004;
        public static final int title_auth=0x7f050001;
        public static final int title_reader=0x7f050002;
    }
    public static final class style {
        public static final int Animation_EInk_NoAnimation=0x7f060001;
        public static final int Theme_EInk=0x7f060000;
    }
}
